Rebranding of the project
freelensapp/freelens pull request #16
Opened 2024-08-21 19:59 UTC by dex4er

* Icons changed
* URLs changed
* Removed all mkdocs as we do not host it nor use the pipelines to build it
* Removed configuration for ADRs
* Removed docs with outdated links
* Removed code of conduct as we need a total new one

2024-08-22 19:50 UTC, dex4er commented
This huge PR completes #3 except email.

2024-08-24 14:34 UTC, dex4er commented
Email is rebranded too

2024-08-25 19:37 UTC, dex4er commented
I'm going to renumber packages from 6.5.0 and others back to 0.1.0

2024-08-26 20:00 UTC, dex4er commented
In the result: changing NPM namespace and version breaks the compatibility for Lens plugins. However, I don't see any sense to have it as it was compatible only for major versions.

2024-08-27 16:38 UTC, robertobandini requested changes

2024-08-27 16:38 UTC, robertobandini commented on packages/business-features/keyboard-shortcuts/package.json
Maybe you missed to change OpenLens to Freelens authors also in these files?

2024-08-27 17:34 UTC, dex4er commented on packages/business-features/keyboard-shortcuts/package.json
It looks like. Ok I'll check if there are some leftovers and we're ready for merge

2024-08-27 19:13 UTC, dex4er commented on packages/business-features/keyboard-shortcuts/package.json
Updated all package.json files

2024-09-22 14:21 UTC, robertobandini approved these changes

2024-09-22 14:24 UTC, merged